//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BaseProto.proto
namespace BaseProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IukMessageBase")]
  public partial class IukMessageBase : global::ProtoBuf.IExtensible
  {
    public IukMessageBase() {}
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _mainId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mainId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mainId
    {
      get { return _mainId; }
      set { _mainId = value; }
    }
    private string _subId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"subId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string subId
    {
      get { return _subId; }
      set { _subId = value; }
    }
    private byte[] _dataContent = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dataContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] dataContent
    {
      get { return _dataContent; }
      set { _dataContent = value; }
    }
    private string _key = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _cmdId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"cmdId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cmdId
    {
      get { return _cmdId; }
      set { _cmdId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}