namespace Iuker.UnityKit.Editor
{
    public enum EditorTextureType
    {
        QArrowDownButton = 0,
        QArrowUpButton = 1,
        QCheckBoxChecked = 2,
        QCheckBoxUnchecked = 3,
        QColorButton = 4,
        QColorPalette = 5,
        QComponentUnknownIcon = 6,
        QErrorChildIcon = 7,
        QErrorIcon = 8,
        QLockOffButton = 9,
        QLockOnButton = 10,
        QMonoBehaviourIcon = 11,
        QMonoBehaviourIconParent = 12,
        QPrefabConnectedIcon = 13,
        QPrefabDisconnectedIcon = 14,
        QRendererOffButton = 15,
        QRendererOnButton = 16,
        QRendererWireframeButton = 17,
        QStaticHalfButton = 18,
        QStaticOffButton = 19,
        QStaticOnButton = 20,
        QTreeMap = 21,
        QTreeMapParent = 22,
        QTrimIcon = 23,
        QVisibilityOffButton = 24,
        QVisibilityOffEditButton = 25,
        QVisibilityOffParentButton = 26,
        QVisibilityOffParentEditButton = 27,
        QVisibilityOnButton = 28,
        QVisibilityOnEditButton = 29,
    }
}