//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DongY_Wolong_ProtoDefine.proto
namespace DongY_Wolong_ProtoDefine
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LHandshakeMQData")]
  public partial class LHandshakeMQData : global::ProtoBuf.IExtensible
  {
    public LHandshakeMQData() {}
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WoLong_PlayerScore")]
  public partial class WoLong_PlayerScore : global::ProtoBuf.IExtensible
  {
    public WoLong_PlayerScore() {}
    
    private int _awardScore = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"awardScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awardScore
    {
      get { return _awardScore; }
      set { _awardScore = value; }
    }
    private int _gatherScore = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gatherScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gatherScore
    {
      get { return _gatherScore; }
      set { _gatherScore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WolongCreateOption")]
  public partial class WolongCreateOption : global::ProtoBuf.IExtensible
  {
    public WolongCreateOption() {}
    
    private int _playerCount = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private int _sameAward = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sameAward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sameAward
    {
      get { return _sameAward; }
      set { _sameAward = value; }
    }
    private int _lianAward = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lianAward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lianAward
    {
      get { return _lianAward; }
      set { _lianAward = value; }
    }
    private bool _singleAward = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"singleAward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool singleAward
    {
      get { return _singleAward; }
      set { _singleAward = value; }
    }
    private bool _singleDouble = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"singleDouble", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool singleDouble
    {
      get { return _singleDouble; }
      set { _singleDouble = value; }
    }
    private int _autoOperate = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"autoOperate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int autoOperate
    {
      get { return _autoOperate; }
      set { _autoOperate = value; }
    }
    private int _dealCardsNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"dealCardsNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dealCardsNum
    {
      get { return _dealCardsNum; }
      set { _dealCardsNum = value; }
    }
    private int _rate = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rate
    {
      get { return _rate; }
      set { _rate = value; }
    }
    private int _breakScoreAward = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"breakScoreAward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int breakScoreAward
    {
      get { return _breakScoreAward; }
      set { _breakScoreAward = value; }
    }
    private int _fanJiangPattern = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"fanJiangPattern", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fanJiangPattern
    {
      get { return _fanJiangPattern; }
      set { _fanJiangPattern = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_AutoOperateMsg")]
  public partial class CTS_WoLong_AutoOperateMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_AutoOperateMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_CoutinueMsg")]
  public partial class CTS_WoLong_CoutinueMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_CoutinueMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_HintMsg")]
  public partial class CTS_WoLong_HintMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_HintMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_OperateMsg")]
  public partial class CTS_WoLong_OperateMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_OperateMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _actonId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"actonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int actonId
    {
      get { return _actonId; }
      set { _actonId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_ReadyMsg")]
  public partial class CTS_WoLong_ReadyMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_ReadyMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_ReconnectMsg")]
  public partial class CTS_WoLong_ReconnectMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_ReconnectMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_RecordMsg")]
  public partial class CTS_WoLong_RecordMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_RecordMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _bankId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bankId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankId
    {
      get { return _bankId; }
      set { _bankId = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_AutoOperateMsg")]
  public partial class STC_WoLong_AutoOperateMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_AutoOperateMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_ContinueMsg")]
  public partial class STC_WoLong_ContinueMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_ContinueMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _password = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _gameStatus = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gameStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameStatus
    {
      get { return _gameStatus; }
      set { _gameStatus = value; }
    }
    private int _actionId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"actionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int actionId
    {
      get { return _actionId; }
      set { _actionId = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private readonly global::System.Collections.Generic.List<WoLongPlayerInfo> _playerList = new global::System.Collections.Generic.List<WoLongPlayerInfo>();
    [global::ProtoBuf.ProtoMember(8, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WoLongPlayerInfo> playerList
    {
      get { return _playerList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private int _operatePosId = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"operatePosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int operatePosId
    {
      get { return _operatePosId; }
      set { _operatePosId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _oerateBeCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"oerateBeCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> oerateBeCards
    {
      get { return _oerateBeCards; }
    }
  
    private int _bePosId = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"bePosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bePosId
    {
      get { return _bePosId; }
      set { _bePosId = value; }
    }
    private WolongCreateOption _option = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WolongCreateOption option
    {
      get { return _option; }
      set { _option = value; }
    }
    private long _clubId = default(long);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WoLongPlayerInfo")]
  public partial class WoLongPlayerInfo : global::ProtoBuf.IExtensible
  {
    public WoLongPlayerInfo() {}
    
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _cardNum = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardNum
    {
      get { return _cardNum; }
      set { _cardNum = value; }
    }
    private int _you = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"you", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int you
    {
      get { return _you; }
      set { _you = value; }
    }
    private int _grade = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private SimplePlayer _player = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SimplePlayer player
    {
      get { return _player; }
      set { _player = value; }
    }
    private int _awardScore = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"awardScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awardScore
    {
      get { return _awardScore; }
      set { _awardScore = value; }
    }
    private int _gatherScore = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gatherScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gatherScore
    {
      get { return _gatherScore; }
      set { _gatherScore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SimplePlayer")]
  public partial class SimplePlayer : global::ProtoBuf.IExtensible
  {
    public SimplePlayer() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _headImg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _gameNum = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gameNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameNum
    {
      get { return _gameNum; }
      set { _gameNum = value; }
    }
    private int _gps_x = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"gps_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_x
    {
      get { return _gps_x; }
      set { _gps_x = value; }
    }
    private int _gps_y = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"gps_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_y
    {
      get { return _gps_y; }
      set { _gps_y = value; }
    }
    private string _gps_address = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"gps_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gps_address
    {
      get { return _gps_address; }
      set { _gps_address = value; }
    }
    private int _online = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private string _introduce = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"introduce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string introduce
    {
      get { return _introduce; }
      set { _introduce = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_HintMsg")]
  public partial class STC_WoLong_HintMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_HintMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private readonly global::System.Collections.Generic.List<CardGroup> _cardsList = new global::System.Collections.Generic.List<CardGroup>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardsList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CardGroup> cardsList
    {
      get { return _cardsList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _beCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"beCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> beCards
    {
      get { return _beCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardGroup")]
  public partial class CardGroup : global::ProtoBuf.IExtensible
  {
    public CardGroup() {}
    
    private readonly global::System.Collections.Generic.List<int> _item = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_OperateMsg")]
  public partial class STC_WoLong_OperateMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_OperateMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _actonId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"actonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int actonId
    {
      get { return _actonId; }
      set { _actonId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private int _awardScore = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"awardScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int awardScore
    {
      get { return _awardScore; }
      set { _awardScore = value; }
    }
    private int _sameAward = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sameAward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sameAward
    {
      get { return _sameAward; }
      set { _sameAward = value; }
    }
    private int _continuousAward = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"continuousAward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int continuousAward
    {
      get { return _continuousAward; }
      set { _continuousAward = value; }
    }
    private int _gatherScore = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gatherScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gatherScore
    {
      get { return _gatherScore; }
      set { _gatherScore = value; }
    }
    private int _gatherScoreosId = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"gatherScoreosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gatherScoreosId
    {
      get { return _gatherScoreosId; }
      set { _gatherScoreosId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _you = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"you", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> you
    {
      get { return _you; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_OperateNoticeMsg")]
  public partial class STC_WoLong_OperateNoticeMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_OperateNoticeMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _beCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"beCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> beCards
    {
      get { return _beCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_ReadyMsg")]
  public partial class STC_WoLong_ReadyMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_ReadyMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_ReconnectMsg")]
  public partial class STC_WoLong_ReconnectMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_ReconnectMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _password = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _gameStatus = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gameStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameStatus
    {
      get { return _gameStatus; }
      set { _gameStatus = value; }
    }
    private int _actionId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"actionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int actionId
    {
      get { return _actionId; }
      set { _actionId = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private readonly global::System.Collections.Generic.List<WoLongPlayerInfo> _playerList = new global::System.Collections.Generic.List<WoLongPlayerInfo>();
    [global::ProtoBuf.ProtoMember(9, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<WoLongPlayerInfo> playerList
    {
      get { return _playerList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private int _operatePosId = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"operatePosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int operatePosId
    {
      get { return _operatePosId; }
      set { _operatePosId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _oerateBeCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"oerateBeCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> oerateBeCards
    {
      get { return _oerateBeCards; }
    }
  
    private int _bePosId = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"bePosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bePosId
    {
      get { return _bePosId; }
      set { _bePosId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_RecordMsg")]
  public partial class STC_WoLong_RecordMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_RecordMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _bankId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bankId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankId
    {
      get { return _bankId; }
      set { _bankId = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private int _handCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handCount
    {
      get { return _handCount; }
      set { _handCount = value; }
    }
    private WolongCreateOption _option = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WolongCreateOption option
    {
      get { return _option; }
      set { _option = value; }
    }
    private readonly global::System.Collections.Generic.List<PlayerInfo> _playerList = new global::System.Collections.Generic.List<PlayerInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerInfo> playerList
    {
      get { return _playerList; }
    }
  
    private readonly global::System.Collections.Generic.List<STC_WoLong_OperateMsg> _operateHistory = new global::System.Collections.Generic.List<STC_WoLong_OperateMsg>();
    [global::ProtoBuf.ProtoMember(7, Name=@"operateHistory", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<STC_WoLong_OperateMsg> operateHistory
    {
      get { return _operateHistory; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_SettleMsg")]
  public partial class STC_WoLong_SettleMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_SettleMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _snId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"snId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int snId
    {
      get { return _snId; }
      set { _snId = value; }
    }
    private int _handTotal = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"handTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handTotal
    {
      get { return _handTotal; }
      set { _handTotal = value; }
    }
    private string _startTime = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private int _bankId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bankId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankId
    {
      get { return _bankId; }
      set { _bankId = value; }
    }
    private int _rate = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rate
    {
      get { return _rate; }
      set { _rate = value; }
    }
    private readonly global::System.Collections.Generic.List<EndPokerMsg> _info = new global::System.Collections.Generic.List<EndPokerMsg>();
    [global::ProtoBuf.ProtoMember(7, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EndPokerMsg> info
    {
      get { return _info; }
    }
  
    private readonly global::System.Collections.Generic.List<EndRankMsg> _rank = new global::System.Collections.Generic.List<EndRankMsg>();
    [global::ProtoBuf.ProtoMember(8, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EndRankMsg> rank
    {
      get { return _rank; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EndRankMsg")]
  public partial class EndRankMsg : global::ProtoBuf.IExtensible
  {
    public EndRankMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _totalScore = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"totalScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalScore
    {
      get { return _totalScore; }
      set { _totalScore = value; }
    }
    private int _maxBomb = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxBomb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxBomb
    {
      get { return _maxBomb; }
      set { _maxBomb = value; }
    }
    private int _bombCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bombCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bombCount
    {
      get { return _bombCount; }
      set { _bombCount = value; }
    }
    private int _isHost = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isHost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isHost
    {
      get { return _isHost; }
      set { _isHost = value; }
    }
    private long _winPlayer = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"winPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long winPlayer
    {
      get { return _winPlayer; }
      set { _winPlayer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EndPokerMsg")]
  public partial class EndPokerMsg : global::ProtoBuf.IExtensible
  {
    public EndPokerMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _poker = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"poker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> poker
    {
      get { return _poker; }
    }
  
    private int _bomb = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bomb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bomb
    {
      get { return _bomb; }
      set { _bomb = value; }
    }
    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _extraScore = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"extraScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int extraScore
    {
      get { return _extraScore; }
      set { _extraScore = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private int _win = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int win
    {
      get { return _win; }
      set { _win = value; }
    }
    private int _totalScore = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"totalScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalScore
    {
      get { return _totalScore; }
      set { _totalScore = value; }
    }
    private int _you = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"you", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int you
    {
      get { return _you; }
      set { _you = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _otherPoker = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"otherPoker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> otherPoker
    {
      get { return _otherPoker; }
    }
  
    private int _baseScore = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"baseScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int baseScore
    {
      get { return _baseScore; }
      set { _baseScore = value; }
    }
    private BigBombMsg _maxBomb = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"maxBomb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BigBombMsg maxBomb
    {
      get { return _maxBomb; }
      set { _maxBomb = value; }
    }
    private int _supply = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"supply", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int supply
    {
      get { return _supply; }
      set { _supply = value; }
    }
    private int _unique = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"unique", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int unique
    {
      get { return _unique; }
      set { _unique = value; }
    }
    private int _noAward = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"noAward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int noAward
    {
      get { return _noAward; }
      set { _noAward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BigBombMsg")]
  public partial class BigBombMsg : global::ProtoBuf.IExtensible
  {
    public BigBombMsg() {}
    
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _hex = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"hex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> hex
    {
      get { return _hex; }
    }
  
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _extraScore = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"extraScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int extraScore
    {
      get { return _extraScore; }
      set { _extraScore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_StartMsg")]
  public partial class STC_WoLong_StartMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_StartMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _bankId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bankId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankId
    {
      get { return _bankId; }
      set { _bankId = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_TableSettleMsg")]
  public partial class CTS_WoLong_TableSettleMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_TableSettleMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_Table_ActExitTableMsg")]
  public partial class CTS_WoLong_Table_ActExitTableMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_Table_ActExitTableMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_Table_ActInTableMsg")]
  public partial class CTS_WoLong_Table_ActInTableMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_Table_ActInTableMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _gps_x = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gps_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_x
    {
      get { return _gps_x; }
      set { _gps_x = value; }
    }
    private int _gps_y = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gps_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_y
    {
      get { return _gps_y; }
      set { _gps_y = value; }
    }
    private string _gps_address = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gps_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gps_address
    {
      get { return _gps_address; }
      set { _gps_address = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_Table_CreateMsg")]
  public partial class CTS_WoLong_Table_CreateMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_Table_CreateMsg() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handTotal = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handTotal
    {
      get { return _handTotal; }
      set { _handTotal = value; }
    }
    private WolongCreateOption _option = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WolongCreateOption option
    {
      get { return _option; }
      set { _option = value; }
    }
    private int _gps_x = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gps_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_x
    {
      get { return _gps_x; }
      set { _gps_x = value; }
    }
    private int _gps_y = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gps_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_y
    {
      get { return _gps_y; }
      set { _gps_y = value; }
    }
    private string _gps_address = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gps_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gps_address
    {
      get { return _gps_address; }
      set { _gps_address = value; }
    }
    private long _clubId = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_Table_DissolveRequestMsg")]
  public partial class CTS_WoLong_Table_DissolveRequestMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_Table_DissolveRequestMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_Table_DissolveVoteMsg")]
  public partial class CTS_WoLong_Table_DissolveVoteMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_Table_DissolveVoteMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _vote = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"vote", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vote
    {
      get { return _vote; }
      set { _vote = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_WoLong_Table_HeartbeatMsg")]
  public partial class CTS_WoLong_Table_HeartbeatMsg : global::ProtoBuf.IExtensible
  {
    public CTS_WoLong_Table_HeartbeatMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_Table_ActExitTableMsg")]
  public partial class STC_WoLong_Table_ActExitTableMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_Table_ActExitTableMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_Table_ActInTableMsg")]
  public partial class STC_WoLong_Table_ActInTableMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_Table_ActInTableMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _password = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private readonly global::System.Collections.Generic.List<SimplePlayer> _playerList = new global::System.Collections.Generic.List<SimplePlayer>();
    [global::ProtoBuf.ProtoMember(5, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SimplePlayer> playerList
    {
      get { return _playerList; }
    }
  
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private WolongCreateOption _option = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WolongCreateOption option
    {
      get { return _option; }
      set { _option = value; }
    }
    private long _clubId = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"clubId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long clubId
    {
      get { return _clubId; }
      set { _clubId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeoError")]
  public partial class TeoError : global::ProtoBuf.IExtensible
  {
    public TeoError() {}
    
    private int _errId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errId
    {
      get { return _errId; }
      set { _errId = value; }
    }
    private string _errMsg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errMsg
    {
      get { return _errMsg; }
      set { _errMsg = value; }
    }
    private bool _isShow = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isShow
    {
      get { return _isShow; }
      set { _isShow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_Table_ActInTable_PublishMsg")]
  public partial class STC_WoLong_Table_ActInTable_PublishMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_Table_ActInTable_PublishMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private SimplePlayer _player = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SimplePlayer player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_Table_CreateMsg")]
  public partial class STC_WoLong_Table_CreateMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_Table_CreateMsg() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handTotal = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handTotal
    {
      get { return _handTotal; }
      set { _handTotal = value; }
    }
    private WolongCreateOption _option = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public WolongCreateOption option
    {
      get { return _option; }
      set { _option = value; }
    }
    private CreateResult _createResult = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"createResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CreateResult createResult
    {
      get { return _createResult; }
      set { _createResult = value; }
    }
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateResult")]
  public partial class CreateResult : global::ProtoBuf.IExtensible
  {
    public CreateResult() {}
    
    private long _masterId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"masterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long masterId
    {
      get { return _masterId; }
      set { _masterId = value; }
    }
    private int _password = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int password
    {
      get { return _password; }
      set { _password = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _createTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_Table_DissolveRequestMsg")]
  public partial class STC_WoLong_Table_DissolveRequestMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_Table_DissolveRequestMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_Table_DissolveResultMsg")]
  public partial class STC_WoLong_Table_DissolveResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_Table_DissolveResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_Table_DissolveVoteMsg")]
  public partial class STC_WoLong_Table_DissolveVoteMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_Table_DissolveVoteMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _reqUserId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reqUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long reqUserId
    {
      get { return _reqUserId; }
      set { _reqUserId = value; }
    }
    private string _reqNickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reqNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reqNickName
    {
      get { return _reqNickName; }
      set { _reqNickName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_Table_DissolveVoteResultMsg")]
  public partial class STC_WoLong_Table_DissolveVoteResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_Table_DissolveVoteResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_WoLong_Table_HeartbeatMsg")]
  public partial class STC_WoLong_Table_HeartbeatMsg : global::ProtoBuf.IExtensible
  {
    public STC_WoLong_Table_HeartbeatMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}