//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DongY_FoolMahJong_ProtoDefine.proto
namespace DongY_FoolMahJong_ProtoDefine
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LHandshakeMQData")]
  public partial class LHandshakeMQData : global::ProtoBuf.IExtensible
  {
    public LHandshakeMQData() {}
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SgmjOption")]
  public partial class SgmjOption : global::ProtoBuf.IExtensible
  {
    public SgmjOption() {}
    
    private int _play = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"play", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int play
    {
      get { return _play; }
      set { _play = value; }
    }
    private int _bottomPoints = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bottomPoints", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bottomPoints
    {
      get { return _bottomPoints; }
      set { _bottomPoints = value; }
    }
    private int _playerSize = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerSize
    {
      get { return _playerSize; }
      set { _playerSize = value; }
    }
    private int _bigOption = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bigOption", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bigOption
    {
      get { return _bigOption; }
      set { _bigOption = value; }
    }
    private int _buyBottom = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"buyBottom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyBottom
    {
      get { return _buyBottom; }
      set { _buyBottom = value; }
    }
    private int _catchBird = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"catchBird", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int catchBird
    {
      get { return _catchBird; }
      set { _catchBird = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Sgmj_ActionMsg")]
  public partial class CTS_Sgmj_ActionMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Sgmj_ActionMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Sgmj_BuyBottomMsg")]
  public partial class CTS_Sgmj_BuyBottomMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Sgmj_BuyBottomMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _buyBottom = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buyBottom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyBottom
    {
      get { return _buyBottom; }
      set { _buyBottom = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_ActionMsg")]
  public partial class STC_Sgmj_ActionMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_ActionMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private int _buCard = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buCard
    {
      get { return _buCard; }
      set { _buCard = value; }
    }
    private int _isWaiting = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isWaiting", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isWaiting
    {
      get { return _isWaiting; }
      set { _isWaiting = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _mahjongCount = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mahjongCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mahjongCount
    {
      get { return _mahjongCount; }
      set { _mahjongCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_BuyBottomMsg")]
  public partial class STC_Sgmj_BuyBottomMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_BuyBottomMsg() {}
    
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _buyBottom = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"buyBottom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyBottom
    {
      get { return _buyBottom; }
      set { _buyBottom = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeoError")]
  public partial class TeoError : global::ProtoBuf.IExtensible
  {
    public TeoError() {}
    
    private int _errId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errId
    {
      get { return _errId; }
      set { _errId = value; }
    }
    private string _errMsg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errMsg
    {
      get { return _errMsg; }
      set { _errMsg = value; }
    }
    private bool _isShow = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isShow
    {
      get { return _isShow; }
      set { _isShow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_MoCardBCMsg")]
  public partial class STC_Sgmj_MoCardBCMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_MoCardBCMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _card = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int card
    {
      get { return _card; }
      set { _card = value; }
    }
    private int _mahjongCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mahjongCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mahjongCount
    {
      get { return _mahjongCount; }
      set { _mahjongCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_NoticeActionMsg")]
  public partial class STC_Sgmj_NoticeActionMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_NoticeActionMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _cardHex = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cardHex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardHex
    {
      get { return _cardHex; }
      set { _cardHex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_NoticeBuyBottomBCMsg")]
  public partial class STC_Sgmj_NoticeBuyBottomBCMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_NoticeBuyBottomBCMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_ReadyHandMsg")]
  public partial class STC_Sgmj_ReadyHandMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_ReadyHandMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_SettleBCMsg")]
  public partial class STC_Sgmj_SettleBCMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_SettleBCMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _snId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"snId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int snId
    {
      get { return _snId; }
      set { _snId = value; }
    }
    private int _handTotal = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"handTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handTotal
    {
      get { return _handTotal; }
      set { _handTotal = value; }
    }
    private string _startTime = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private int _cardHex = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cardHex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardHex
    {
      get { return _cardHex; }
      set { _cardHex = value; }
    }
    private int _huType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"huType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int huType
    {
      get { return _huType; }
      set { _huType = value; }
    }
    private readonly global::System.Collections.Generic.List<EndResultMsg> _endResultMsgs = new global::System.Collections.Generic.List<EndResultMsg>();
    [global::ProtoBuf.ProtoMember(7, Name=@"endResultMsgs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EndResultMsg> endResultMsgs
    {
      get { return _endResultMsgs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EndResultMsg")]
  public partial class EndResultMsg : global::ProtoBuf.IExtensible
  {
    public EndResultMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private readonly global::System.Collections.Generic.List<MahjongInfos> _mahjongInfosBuild = new global::System.Collections.Generic.List<MahjongInfos>();
    [global::ProtoBuf.ProtoMember(3, Name=@"mahjongInfosBuild", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MahjongInfos> mahjongInfosBuild
    {
      get { return _mahjongInfosBuild; }
    }
  
    private int _huType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"huType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int huType
    {
      get { return _huType; }
      set { _huType = value; }
    }
    private int _supportWinType = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"supportWinType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int supportWinType
    {
      get { return _supportWinType; }
      set { _supportWinType = value; }
    }
    private int _behuType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"behuType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int behuType
    {
      get { return _behuType; }
      set { _behuType = value; }
    }
    private int _birdNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"birdNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int birdNum
    {
      get { return _birdNum; }
      set { _birdNum = value; }
    }
    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _totalScore = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"totalScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalScore
    {
      get { return _totalScore; }
      set { _totalScore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MahjongInfos")]
  public partial class MahjongInfos : global::ProtoBuf.IExtensible
  {
    public MahjongInfos() {}
    
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cradHex = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cradHex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cradHex
    {
      get { return _cradHex; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_StartBCMsg")]
  public partial class STC_Sgmj_StartBCMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_StartBCMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _buyBottom = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"buyBottom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> buyBottom
    {
      get { return _buyBottom; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private long _bankerUserId = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bankerUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bankerUserId
    {
      get { return _bankerUserId; }
      set { _bankerUserId = value; }
    }
    private int _a = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"a", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int a
    {
      get { return _a; }
      set { _a = value; }
    }
    private int _b = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int b
    {
      get { return _b; }
      set { _b = value; }
    }
    private int _mahjongCount = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mahjongCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mahjongCount
    {
      get { return _mahjongCount; }
      set { _mahjongCount = value; }
    }
    private int _leftTime = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"leftTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int leftTime
    {
      get { return _leftTime; }
      set { _leftTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Sgmj_Table_CreateMsg")]
  public partial class CTS_Sgmj_Table_CreateMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Sgmj_Table_CreateMsg() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handTotal = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handTotal
    {
      get { return _handTotal; }
      set { _handTotal = value; }
    }
    private int _gps_x = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gps_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_x
    {
      get { return _gps_x; }
      set { _gps_x = value; }
    }
    private int _gps_y = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gps_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_y
    {
      get { return _gps_y; }
      set { _gps_y = value; }
    }
    private string _gps_address = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gps_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gps_address
    {
      get { return _gps_address; }
      set { _gps_address = value; }
    }
    private SgmjOption _sgmjOption = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sgmjOption", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SgmjOption sgmjOption
    {
      get { return _sgmjOption; }
      set { _sgmjOption = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Sgmj_Table_DissolveVoteMsg")]
  public partial class CTS_Sgmj_Table_DissolveVoteMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Sgmj_Table_DissolveVoteMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _vote = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"vote", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vote
    {
      get { return _vote; }
      set { _vote = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Sgmj_Table_ExitMsg")]
  public partial class CTS_Sgmj_Table_ExitMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Sgmj_Table_ExitMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Sgmj_Table_InMsg")]
  public partial class CTS_Sgmj_Table_InMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Sgmj_Table_InMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _password = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int password
    {
      get { return _password; }
      set { _password = value; }
    }
    private int _gps_x = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gps_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_x
    {
      get { return _gps_x; }
      set { _gps_x = value; }
    }
    private int _gps_y = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gps_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_y
    {
      get { return _gps_y; }
      set { _gps_y = value; }
    }
    private string _gps_address = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gps_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gps_address
    {
      get { return _gps_address; }
      set { _gps_address = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Sgmj_Table_ReadyMsg")]
  public partial class CTS_Sgmj_Table_ReadyMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Sgmj_Table_ReadyMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private bool _isReady = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isReady", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isReady
    {
      get { return _isReady; }
      set { _isReady = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Sgmj_Table_ReconnectMsg")]
  public partial class CTS_Sgmj_Table_ReconnectMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Sgmj_Table_ReconnectMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Sgmj_Table_ReqDissolveMsg")]
  public partial class CTS_Sgmj_Table_ReqDissolveMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Sgmj_Table_ReqDissolveMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_Table_CreateMsg")]
  public partial class STC_Sgmj_Table_CreateMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_Table_CreateMsg() {}
    
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private int _password = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int password
    {
      get { return _password; }
      set { _password = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _createTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handTotal = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"handTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handTotal
    {
      get { return _handTotal; }
      set { _handTotal = value; }
    }
    private int _playerCount = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"playerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerCount
    {
      get { return _playerCount; }
      set { _playerCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_Table_DissolveBCMsg")]
  public partial class STC_Sgmj_Table_DissolveBCMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_Table_DissolveBCMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _isSucc = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isSucc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isSucc
    {
      get { return _isSucc; }
      set { _isSucc = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _agree = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> agree
    {
      get { return _agree; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _disagree = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"disagree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> disagree
    {
      get { return _disagree; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_Table_DissolveVoteMsg")]
  public partial class STC_Sgmj_Table_DissolveVoteMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_Table_DissolveVoteMsg() {}
    
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_Table_ExitMsg")]
  public partial class STC_Sgmj_Table_ExitMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_Table_ExitMsg() {}
    
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_Table_InMsg")]
  public partial class STC_Sgmj_Table_InMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_Table_InMsg() {}
    
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _pos = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private long _password = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private readonly global::System.Collections.Generic.List<SimplePlayer> _playerList = new global::System.Collections.Generic.List<SimplePlayer>();
    [global::ProtoBuf.ProtoMember(8, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SimplePlayer> playerList
    {
      get { return _playerList; }
    }
  
    private SgmjOption _sgmjOption = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"sgmjOption", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SgmjOption sgmjOption
    {
      get { return _sgmjOption; }
      set { _sgmjOption = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SimplePlayer")]
  public partial class SimplePlayer : global::ProtoBuf.IExtensible
  {
    public SimplePlayer() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _headImg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _gameNum = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gameNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameNum
    {
      get { return _gameNum; }
      set { _gameNum = value; }
    }
    private int _gps_x = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"gps_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_x
    {
      get { return _gps_x; }
      set { _gps_x = value; }
    }
    private int _gps_y = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"gps_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gps_y
    {
      get { return _gps_y; }
      set { _gps_y = value; }
    }
    private string _gps_address = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"gps_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gps_address
    {
      get { return _gps_address; }
      set { _gps_address = value; }
    }
    private int _online = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private string _introduce = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"introduce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string introduce
    {
      get { return _introduce; }
      set { _introduce = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_Table_InBCMsg")]
  public partial class STC_Sgmj_Table_InBCMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_Table_InBCMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private SimplePlayer _player = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SimplePlayer player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_Table_ReadyBCMsg")]
  public partial class STC_Sgmj_Table_ReadyBCMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_Table_ReadyBCMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private bool _isReady = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isReady", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isReady
    {
      get { return _isReady; }
      set { _isReady = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_Table_ReconnectMsg")]
  public partial class STC_Sgmj_Table_ReconnectMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_Table_ReconnectMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _tableStatus = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tableStatus
    {
      get { return _tableStatus; }
      set { _tableStatus = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private int _dissoveCountdown = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dissoveCountdown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dissoveCountdown
    {
      get { return _dissoveCountdown; }
      set { _dissoveCountdown = value; }
    }
    private readonly global::System.Collections.Generic.List<PosInfo> _playerList = new global::System.Collections.Generic.List<PosInfo>();
    [global::ProtoBuf.ProtoMember(9, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PosInfo> playerList
    {
      get { return _playerList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private JjzdPlayInfo _jjzdPlayInfo = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"jjzdPlayInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JjzdPlayInfo jjzdPlayInfo
    {
      get { return _jjzdPlayInfo; }
      set { _jjzdPlayInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JjzdPlayInfo")]
  public partial class JjzdPlayInfo : global::ProtoBuf.IExtensible
  {
    public JjzdPlayInfo() {}
    
    private int _gameStatus = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameStatus
    {
      get { return _gameStatus; }
      set { _gameStatus = value; }
    }
    private int _alonePos = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"alonePos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int alonePos
    {
      get { return _alonePos; }
      set { _alonePos = value; }
    }
    private int _operatePosId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"operatePosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int operatePosId
    {
      get { return _operatePosId; }
      set { _operatePosId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _oerateBeCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"oerateBeCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> oerateBeCards
    {
      get { return _oerateBeCards; }
    }
  
    private int _bePosId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bePosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bePosId
    {
      get { return _bePosId; }
      set { _bePosId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PosInfo")]
  public partial class PosInfo : global::ProtoBuf.IExtensible
  {
    public PosInfo() {}
    
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _cardNum = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cardNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardNum
    {
      get { return _cardNum; }
      set { _cardNum = value; }
    }
    private int _grade = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private SimplePlayer _player = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SimplePlayer player
    {
      get { return _player; }
      set { _player = value; }
    }
    private JjzdPosInfo _jjzdPosInfo = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"jjzdPosInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public JjzdPosInfo jjzdPosInfo
    {
      get { return _jjzdPosInfo; }
      set { _jjzdPosInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JjzdPosInfo")]
  public partial class JjzdPosInfo : global::ProtoBuf.IExtensible
  {
    public JjzdPosInfo() {}
    
    private int _you = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"you", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int you
    {
      get { return _you; }
      set { _you = value; }
    }
    private int _plusBuy = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"plusBuy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int plusBuy
    {
      get { return _plusBuy; }
      set { _plusBuy = value; }
    }
    private int _colorNum = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"colorNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int colorNum
    {
      get { return _colorNum; }
      set { _colorNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Sgmj_Table_ReqDissolveMsg")]
  public partial class STC_Sgmj_Table_ReqDissolveMsg : global::ProtoBuf.IExtensible
  {
    public STC_Sgmj_Table_ReqDissolveMsg() {}
    
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private int _tikerTime = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tikerTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tikerTime
    {
      get { return _tikerTime; }
      set { _tikerTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}