//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Jiax_MaJiang_ProtoDefine.proto
namespace Jiax_MaJiang_ProtoDefine
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_ActInTableMsg")]
  public partial class CTS_Table_ActInTableMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_ActInTableMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_CreateMsg")]
  public partial class CTS_Table_CreateMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_CreateMsg() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private string _gameTypes = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gameTypes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameTypes
    {
      get { return _gameTypes; }
      set { _gameTypes = value; }
    }
    private int _startPoint = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"startPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startPoint
    {
      get { return _startPoint; }
      set { _startPoint = value; }
    }
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_DissolveRequestMsg")]
  public partial class CTS_Table_DissolveRequestMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_DissolveRequestMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_DissolveVoteMsg")]
  public partial class CTS_Table_DissolveVoteMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_DissolveVoteMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _vote = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"vote", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vote
    {
      get { return _vote; }
      set { _vote = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_HeartbeatMsg")]
  public partial class CTS_Table_HeartbeatMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_HeartbeatMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_TableSettleMsg")]
  public partial class STC_TableSettleMsg : global::ProtoBuf.IExtensible
  {
    public STC_TableSettleMsg() {}
    
    private readonly global::System.Collections.Generic.List<PlayerGrade> _gradeList = new global::System.Collections.Generic.List<PlayerGrade>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gradeList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerGrade> gradeList
    {
      get { return _gradeList; }
    }
  
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private long _createTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private long _finishTime = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"finishTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long finishTime
    {
      get { return _finishTime; }
      set { _finishTime = value; }
    }
    private int _seatNum = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"seatNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seatNum
    {
      get { return _seatNum; }
      set { _seatNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerGrade")]
  public partial class PlayerGrade : global::ProtoBuf.IExtensible
  {
    public PlayerGrade() {}
    
    private string _avatar = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _winCount = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"winCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winCount
    {
      get { return _winCount; }
      set { _winCount = value; }
    }
    private int _loseCount = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"loseCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int loseCount
    {
      get { return _loseCount; }
      set { _loseCount = value; }
    }
    private int _tieCount = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"tieCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tieCount
    {
      get { return _tieCount; }
      set { _tieCount = value; }
    }
    private int _chengbaoCount = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"chengbaoCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chengbaoCount
    {
      get { return _chengbaoCount; }
      set { _chengbaoCount = value; }
    }
    private int _handMaxGrade = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"handMaxGrade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handMaxGrade
    {
      get { return _handMaxGrade; }
      set { _handMaxGrade = value; }
    }
    private string _fangtai = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"fangtai", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fangtai
    {
      get { return _fangtai; }
      set { _fangtai = value; }
    }
    private int _gradeCount = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"gradeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gradeCount
    {
      get { return _gradeCount; }
      set { _gradeCount = value; }
    }
    private int _isMaster = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"isMaster", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isMaster
    {
      get { return _isMaster; }
      set { _isMaster = value; }
    }
    private int _isWinMax = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"isWinMax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isWinMax
    {
      get { return _isWinMax; }
      set { _isWinMax = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_ActInTableMsg")]
  public partial class STC_Table_ActInTableMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_ActInTableMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _password = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private string _gameTypes = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gameTypes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameTypes
    {
      get { return _gameTypes; }
      set { _gameTypes = value; }
    }
    private int _startPoint = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"startPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startPoint
    {
      get { return _startPoint; }
      set { _startPoint = value; }
    }
    private readonly global::System.Collections.Generic.List<SimplePlayer> _playerList = new global::System.Collections.Generic.List<SimplePlayer>();
    [global::ProtoBuf.ProtoMember(9, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SimplePlayer> playerList
    {
      get { return _playerList; }
    }
  
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeoError")]
  public partial class TeoError : global::ProtoBuf.IExtensible
  {
    public TeoError() {}
    
    private int _errId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errId
    {
      get { return _errId; }
      set { _errId = value; }
    }
    private string _errMsg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errMsg
    {
      get { return _errMsg; }
      set { _errMsg = value; }
    }
    private bool _isShow = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isShow
    {
      get { return _isShow; }
      set { _isShow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SimplePlayer")]
  public partial class SimplePlayer : global::ProtoBuf.IExtensible
  {
    public SimplePlayer() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _headImg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _online = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _gameCount = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"gameCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameCount
    {
      get { return _gameCount; }
      set { _gameCount = value; }
    }
    private double _latitude = default(double);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"latitude", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double latitude
    {
      get { return _latitude; }
      set { _latitude = value; }
    }
    private double _longitude = default(double);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"longitude", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double longitude
    {
      get { return _longitude; }
      set { _longitude = value; }
    }
    private string _address = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_ActInTable_PublishMsg")]
  public partial class STC_Table_ActInTable_PublishMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_ActInTable_PublishMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private SimplePlayer _player = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SimplePlayer player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_CreateMsg")]
  public partial class STC_Table_CreateMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_CreateMsg() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private string _gameTypes = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gameTypes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameTypes
    {
      get { return _gameTypes; }
      set { _gameTypes = value; }
    }
    private int _startPoint = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"startPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startPoint
    {
      get { return _startPoint; }
      set { _startPoint = value; }
    }
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private CreateResult _createResult = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"createResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CreateResult createResult
    {
      get { return _createResult; }
      set { _createResult = value; }
    }
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateResult")]
  public partial class CreateResult : global::ProtoBuf.IExtensible
  {
    public CreateResult() {}
    
    private long _masterId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"masterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long masterId
    {
      get { return _masterId; }
      set { _masterId = value; }
    }
    private int _password = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int password
    {
      get { return _password; }
      set { _password = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _createTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_DissolveRequestMsg")]
  public partial class STC_Table_DissolveRequestMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_DissolveRequestMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_DissolveResultMsg")]
  public partial class STC_Table_DissolveResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_DissolveResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_DissolveVoteMsg")]
  public partial class STC_Table_DissolveVoteMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_DissolveVoteMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _reqUserId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reqUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long reqUserId
    {
      get { return _reqUserId; }
      set { _reqUserId = value; }
    }
    private string _reqNickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reqNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reqNickName
    {
      get { return _reqNickName; }
      set { _reqNickName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_DissolveVoteResultMsg")]
  public partial class STC_Table_DissolveVoteResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_DissolveVoteResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_HeartbeatMsg")]
  public partial class STC_Table_HeartbeatMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_HeartbeatMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_ReadyMsg")]
  public partial class CTS_ReadyMsg : global::ProtoBuf.IExtensible
  {
    public CTS_ReadyMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_ReadyMsg")]
  public partial class STC_ReadyMsg : global::ProtoBuf.IExtensible
  {
    public STC_ReadyMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_StartMsg")]
  public partial class STC_StartMsg : global::ProtoBuf.IExtensible
  {
    public STC_StartMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _bankId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bankId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankId
    {
      get { return _bankId; }
      set { _bankId = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private int _bePosId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bePosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bePosId
    {
      get { return _bePosId; }
      set { _bePosId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _cardSize = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"cardSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardSize
    {
      get { return _cardSize; }
    }
  
    private int _guiIndex = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"guiIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guiIndex
    {
      get { return _guiIndex; }
      set { _guiIndex = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _dices = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"dices", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> dices
    {
      get { return _dices; }
    }
  
    private int _cardSurplus = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cardSurplus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardSurplus
    {
      get { return _cardSurplus; }
      set { _cardSurplus = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _quan = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"quan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quan
    {
      get { return _quan; }
      set { _quan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_OperateMsg")]
  public partial class CTS_OperateMsg : global::ProtoBuf.IExtensible
  {
    public CTS_OperateMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_OperateMsg")]
  public partial class STC_OperateMsg : global::ProtoBuf.IExtensible
  {
    public STC_OperateMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _targetCardPosId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"targetCardPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetCardPosId
    {
      get { return _targetCardPosId; }
      set { _targetCardPosId = value; }
    }
    private int _targetCard = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"targetCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetCard
    {
      get { return _targetCard; }
      set { _targetCard = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _otherCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"otherCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> otherCards
    {
      get { return _otherCards; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private int _nextPosId = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"nextPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nextPosId
    {
      get { return _nextPosId; }
      set { _nextPosId = value; }
    }
    private int _cardSurplus = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"cardSurplus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardSurplus
    {
      get { return _cardSurplus; }
      set { _cardSurplus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_OperateNoticeMsg")]
  public partial class STC_OperateNoticeMsg : global::ProtoBuf.IExtensible
  {
    public STC_OperateNoticeMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _beCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"beCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> beCards
    {
      get { return _beCards; }
    }
  
    private int _fromPosId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fromPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fromPosId
    {
      get { return _fromPosId; }
      set { _fromPosId = value; }
    }
    private readonly global::System.Collections.Generic.List<CardList> _cardList = new global::System.Collections.Generic.List<CardList>();
    [global::ProtoBuf.ProtoMember(6, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CardList> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardList")]
  public partial class CardList : global::ProtoBuf.IExtensible
  {
    public CardList() {}
    
    private readonly global::System.Collections.Generic.List<int> _toCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"toCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> toCards
    {
      get { return _toCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_User_OnlineMsg")]
  public partial class STC_Table_User_OnlineMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_User_OnlineMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_QuitMsg")]
  public partial class CTS_Table_QuitMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_QuitMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_Quit_NotificaMsg")]
  public partial class STC_Table_Quit_NotificaMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_Quit_NotificaMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private readonly global::System.Collections.Generic.List<SimplePlayer> _playerList = new global::System.Collections.Generic.List<SimplePlayer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SimplePlayer> playerList
    {
      get { return _playerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_Quit_ResultMsg")]
  public partial class STC_Table_Quit_ResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_Quit_ResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private bool _success = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_OfflineMsg")]
  public partial class CTS_OfflineMsg : global::ProtoBuf.IExtensible
  {
    public CTS_OfflineMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_ChengBaoMsg")]
  public partial class CTS_ChengBaoMsg : global::ProtoBuf.IExtensible
  {
    public CTS_ChengBaoMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _fromPosId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fromPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fromPosId
    {
      get { return _fromPosId; }
      set { _fromPosId = value; }
    }
    private int _toPosId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"toPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int toPosId
    {
      get { return _toPosId; }
      set { _toPosId = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_ChengBaoMsg")]
  public partial class STC_ChengBaoMsg : global::ProtoBuf.IExtensible
  {
    public STC_ChengBaoMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _fromPosId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fromPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fromPosId
    {
      get { return _fromPosId; }
      set { _fromPosId = value; }
    }
    private int _toPosId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"toPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int toPosId
    {
      get { return _toPosId; }
      set { _toPosId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_ChengBaoResultMsg")]
  public partial class STC_ChengBaoResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_ChengBaoResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _valueList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"valueList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> valueList
    {
      get { return _valueList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_ContinueMsg")]
  public partial class CTS_ContinueMsg : global::ProtoBuf.IExtensible
  {
    public CTS_ContinueMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_ContinueMsg")]
  public partial class STC_ContinueMsg : global::ProtoBuf.IExtensible
  {
    public STC_ContinueMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _password = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _gameStatus = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gameStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameStatus
    {
      get { return _gameStatus; }
      set { _gameStatus = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _readyStatus = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"readyStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> readyStatus
    {
      get { return _readyStatus; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _scoreList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"scoreList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> scoreList
    {
      get { return _scoreList; }
    }
  
    private readonly global::System.Collections.Generic.List<SimplePlayer> _playerList = new global::System.Collections.Generic.List<SimplePlayer>();
    [global::ProtoBuf.ProtoMember(9, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SimplePlayer> playerList
    {
      get { return _playerList; }
    }
  
    private int _nextPosId = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"nextPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nextPosId
    {
      get { return _nextPosId; }
      set { _nextPosId = value; }
    }
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private bool _isBeOut = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"isBeOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBeOut
    {
      get { return _isBeOut; }
      set { _isBeOut = value; }
    }
    private int _bankId = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"bankId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankId
    {
      get { return _bankId; }
      set { _bankId = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private readonly global::System.Collections.Generic.List<OPosIdCardInfo> _cpgList = new global::System.Collections.Generic.List<OPosIdCardInfo>();
    [global::ProtoBuf.ProtoMember(15, Name=@"cpgList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OPosIdCardInfo> cpgList
    {
      get { return _cpgList; }
    }
  
    private int _guiIndex = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"guiIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guiIndex
    {
      get { return _guiIndex; }
      set { _guiIndex = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _dices = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(17, Name=@"dices", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> dices
    {
      get { return _dices; }
    }
  
    private int _cardSurplus = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"cardSurplus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardSurplus
    {
      get { return _cardSurplus; }
      set { _cardSurplus = value; }
    }
    private int _quan = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"quan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quan
    {
      get { return _quan; }
      set { _quan = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private string _gameTypes = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"gameTypes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameTypes
    {
      get { return _gameTypes; }
      set { _gameTypes = value; }
    }
    private int _startPoint = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"startPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startPoint
    {
      get { return _startPoint; }
      set { _startPoint = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OPosIdCardInfo")]
  public partial class OPosIdCardInfo : global::ProtoBuf.IExtensible
  {
    public OPosIdCardInfo() {}
    
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private readonly global::System.Collections.Generic.List<OCardAction> _actionList = new global::System.Collections.Generic.List<OCardAction>();
    [global::ProtoBuf.ProtoMember(2, Name=@"actionList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OCardAction> actionList
    {
      get { return _actionList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _outCardList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"outCardList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> outCardList
    {
      get { return _outCardList; }
    }
  
    private int _cardSize = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cardSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardSize
    {
      get { return _cardSize; }
      set { _cardSize = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OCardAction")]
  public partial class OCardAction : global::ProtoBuf.IExtensible
  {
    public OCardAction() {}
    
    private int _userPosId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userPosId
    {
      get { return _userPosId; }
      set { _userPosId = value; }
    }
    private int _action = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private int _targetCard = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"targetCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetCard
    {
      get { return _targetCard; }
      set { _targetCard = value; }
    }
    private int _targetCardPosId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"targetCardPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetCardPosId
    {
      get { return _targetCardPosId; }
      set { _targetCardPosId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cpgCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"cpgCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cpgCards
    {
      get { return _cpgCards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_SettleMsg")]
  public partial class STC_SettleMsg : global::ProtoBuf.IExtensible
  {
    public STC_SettleMsg() {}
    
    private readonly global::System.Collections.Generic.List<SettleItem> _settleLst = new global::System.Collections.Generic.List<SettleItem>();
    [global::ProtoBuf.ProtoMember(1, Name=@"settleLst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SettleItem> settleLst
    {
      get { return _settleLst; }
    }
  
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private string _gameTypes = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gameTypes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameTypes
    {
      get { return _gameTypes; }
      set { _gameTypes = value; }
    }
    private int _startPoint = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"startPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startPoint
    {
      get { return _startPoint; }
      set { _startPoint = value; }
    }
    private int _guiCard = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"guiCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guiCard
    {
      get { return _guiCard; }
      set { _guiCard = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _quan = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"quan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quan
    {
      get { return _quan; }
      set { _quan = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private string _dateDesc = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"dateDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dateDesc
    {
      get { return _dateDesc; }
      set { _dateDesc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SettleItem")]
  public partial class SettleItem : global::ProtoBuf.IExtensible
  {
    public SettleItem() {}
    
    private readonly global::System.Collections.Generic.List<int> _otherCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"otherCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> otherCards
    {
      get { return _otherCards; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _handCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"handCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> handCards
    {
      get { return _handCards; }
    }
  
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private bool _isBank = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isBank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBank
    {
      get { return _isBank; }
      set { _isBank = value; }
    }
    private bool _isWin = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isWin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isWin
    {
      get { return _isWin; }
      set { _isWin = value; }
    }
    private int _winCard = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"winCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winCard
    {
      get { return _winCard; }
      set { _winCard = value; }
    }
    private int _sumScore = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sumScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sumScore
    {
      get { return _sumScore; }
      set { _sumScore = value; }
    }
    private string _scoreDesc = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"scoreDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string scoreDesc
    {
      get { return _scoreDesc; }
      set { _scoreDesc = value; }
    }
    private string _bankDirection = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"bankDirection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bankDirection
    {
      get { return _bankDirection; }
      set { _bankDirection = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_OfflineMsg")]
  public partial class STC_OfflineMsg : global::ProtoBuf.IExtensible
  {
    public STC_OfflineMsg() {}
    
    private readonly global::System.Collections.Generic.List<int> _chengbaoList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"chengbaoList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> chengbaoList
    {
      get { return _chengbaoList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _dices = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"dices", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> dices
    {
      get { return _dices; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _readyStatus = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"readyStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> readyStatus
    {
      get { return _readyStatus; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _scoreList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"scoreList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> scoreList
    {
      get { return _scoreList; }
    }
  
    private readonly global::System.Collections.Generic.List<SimplePlayer> _playerList = new global::System.Collections.Generic.List<SimplePlayer>();
    [global::ProtoBuf.ProtoMember(5, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SimplePlayer> playerList
    {
      get { return _playerList; }
    }
  
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _password = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _gameStatus = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"gameStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameStatus
    {
      get { return _gameStatus; }
      set { _gameStatus = value; }
    }
    private readonly global::System.Collections.Generic.List<OPosIdCardInfo> _cpgList = new global::System.Collections.Generic.List<OPosIdCardInfo>();
    [global::ProtoBuf.ProtoMember(12, Name=@"cpgList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OPosIdCardInfo> cpgList
    {
      get { return _cpgList; }
    }
  
    private int _nextPosId = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"nextPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nextPosId
    {
      get { return _nextPosId; }
      set { _nextPosId = value; }
    }
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private bool _isBeOut = default(bool);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"isBeOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBeOut
    {
      get { return _isBeOut; }
      set { _isBeOut = value; }
    }
    private int _bankId = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"bankId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankId
    {
      get { return _bankId; }
      set { _bankId = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private int _guiIndex = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"guiIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int guiIndex
    {
      get { return _guiIndex; }
      set { _guiIndex = value; }
    }
    private int _cardSurplus = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"cardSurplus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardSurplus
    {
      get { return _cardSurplus; }
      set { _cardSurplus = value; }
    }
    private int _quan = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"quan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quan
    {
      get { return _quan; }
      set { _quan = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private string _gameTypes = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"gameTypes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameTypes
    {
      get { return _gameTypes; }
      set { _gameTypes = value; }
    }
    private int _startPoint = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"startPoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int startPoint
    {
      get { return _startPoint; }
      set { _startPoint = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}