//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Jiax_HongShi_ProtoDefine.proto
namespace Jiax_HongShi_ProtoDefine
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_ContinueMsg")]
  public partial class CTS_Hongshi_ContinueMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_ContinueMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_OperateMsg")]
  public partial class CTS_Hongshi_OperateMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_OperateMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _typeAction = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"typeAction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int typeAction
    {
      get { return _typeAction; }
      set { _typeAction = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_ReadyMsg")]
  public partial class CTS_Hongshi_ReadyMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_ReadyMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_ShowHsMsg")]
  public partial class CTS_Hongshi_ShowHsMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_ShowHsMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private bool _isShowHs = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isShowHs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isShowHs
    {
      get { return _isShowHs; }
      set { _isShowHs = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_OperateMsg")]
  public partial class STC_Hongshi_OperateMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_OperateMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private bool _succeed = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_ReadyMsg")]
  public partial class STC_Hongshi_ReadyMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_ReadyMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_ShowHs_ResultMsg")]
  public partial class STC_Hongshi_ShowHs_ResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_ShowHs_ResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private bool _succeed = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_StartMsg")]
  public partial class STC_Hongshi_StartMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_StartMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _bankId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bankId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankId
    {
      get { return _bankId; }
      set { _bankId = value; }
    }
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private int _bePosId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bePosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bePosId
    {
      get { return _bePosId; }
      set { _bePosId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _cardSize = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"cardSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardSize
    {
      get { return _cardSize; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_WinMsg")]
  public partial class STC_Hongshi_WinMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_WinMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_Table_ActInTableMsg")]
  public partial class CTS_Hongshi_Table_ActInTableMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_Table_ActInTableMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_Table_AgainMsg")]
  public partial class CTS_Hongshi_Table_AgainMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_Table_AgainMsg() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _userIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(7, Name=@"userIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> userIds
    {
      get { return _userIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_Table_CreateMsg")]
  public partial class CTS_Hongshi_Table_CreateMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_Table_CreateMsg() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_Table_DissolveRequestMsg")]
  public partial class CTS_Hongshi_Table_DissolveRequestMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_Table_DissolveRequestMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_Table_DissolveVoteMsg")]
  public partial class CTS_Hongshi_Table_DissolveVoteMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_Table_DissolveVoteMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _vote = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"vote", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vote
    {
      get { return _vote; }
      set { _vote = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_Table_HeartbeatMsg")]
  public partial class CTS_Hongshi_Table_HeartbeatMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_Table_HeartbeatMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_TableSettleMsg")]
  public partial class STC_Hongshi_TableSettleMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_TableSettleMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handTotal = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"handTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handTotal
    {
      get { return _handTotal; }
      set { _handTotal = value; }
    }
    private long _createTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private long _finishTime = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"finishTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long finishTime
    {
      get { return _finishTime; }
      set { _finishTime = value; }
    }
    private string _masterUserHeadImg = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"masterUserHeadImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string masterUserHeadImg
    {
      get { return _masterUserHeadImg; }
      set { _masterUserHeadImg = value; }
    }
    private int _seatNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"seatNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seatNum
    {
      get { return _seatNum; }
      set { _seatNum = value; }
    }
    private readonly global::System.Collections.Generic.List<PlayerHongshiGrade> _gradeList = new global::System.Collections.Generic.List<PlayerHongshiGrade>();
    [global::ProtoBuf.ProtoMember(8, Name=@"gradeList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerHongshiGrade> gradeList
    {
      get { return _gradeList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerHongshiGrade")]
  public partial class PlayerHongshiGrade : global::ProtoBuf.IExtensible
  {
    public PlayerHongshiGrade() {}
    
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _winCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"winCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winCount
    {
      get { return _winCount; }
      set { _winCount = value; }
    }
    private int _loseCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"loseCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int loseCount
    {
      get { return _loseCount; }
      set { _loseCount = value; }
    }
    private int _tieCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tieCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tieCount
    {
      get { return _tieCount; }
      set { _tieCount = value; }
    }
    private int _handMaxGrade = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"handMaxGrade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handMaxGrade
    {
      get { return _handMaxGrade; }
      set { _handMaxGrade = value; }
    }
    private int _topCount = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"topCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int topCount
    {
      get { return _topCount; }
      set { _topCount = value; }
    }
    private int _gradeCount = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gradeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gradeCount
    {
      get { return _gradeCount; }
      set { _gradeCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_Again_NotificaMsg")]
  public partial class STC_Hongshi_Table_Again_NotificaMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_Again_NotificaMsg() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_DissolveRequestMsg")]
  public partial class STC_Hongshi_Table_DissolveRequestMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_DissolveRequestMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeoError")]
  public partial class TeoError : global::ProtoBuf.IExtensible
  {
    public TeoError() {}
    
    private int _errId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errId
    {
      get { return _errId; }
      set { _errId = value; }
    }
    private string _errMsg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errMsg
    {
      get { return _errMsg; }
      set { _errMsg = value; }
    }
    private bool _isShow = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isShow
    {
      get { return _isShow; }
      set { _isShow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_DissolveResultMsg")]
  public partial class STC_Hongshi_Table_DissolveResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_DissolveResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_DissolveVoteMsg")]
  public partial class STC_Hongshi_Table_DissolveVoteMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_DissolveVoteMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _reqUserId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reqUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long reqUserId
    {
      get { return _reqUserId; }
      set { _reqUserId = value; }
    }
    private string _reqNickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reqNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reqNickName
    {
      get { return _reqNickName; }
      set { _reqNickName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_DissolveVoteResultMsg")]
  public partial class STC_Hongshi_Table_DissolveVoteResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_DissolveVoteResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_HeartbeatMsg")]
  public partial class STC_Hongshi_Table_HeartbeatMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_HeartbeatMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_CreateMsg")]
  public partial class STC_Hongshi_Table_CreateMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_CreateMsg() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private CreateHongshiResult _createResult = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"createResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CreateHongshiResult createResult
    {
      get { return _createResult; }
      set { _createResult = value; }
    }
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateHongshiResult")]
  public partial class CreateHongshiResult : global::ProtoBuf.IExtensible
  {
    public CreateHongshiResult() {}
    
    private long _masterId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"masterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long masterId
    {
      get { return _masterId; }
      set { _masterId = value; }
    }
    private int _password = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int password
    {
      get { return _password; }
      set { _password = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _createTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_OfflineMsg")]
  public partial class CTS_Hongshi_OfflineMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_OfflineMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Hongshi_Table_QuitMsg")]
  public partial class CTS_Hongshi_Table_QuitMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Hongshi_Table_QuitMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_Quit_ResultMsg")]
  public partial class STC_Hongshi_Table_Quit_ResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_Quit_ResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private bool _success = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool success
    {
      get { return _success; }
      set { _success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_ShowHsMsg")]
  public partial class STC_Hongshi_ShowHsMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_ShowHsMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _showCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"showCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> showCards
    {
      get { return _showCards; }
    }
  
    private bool _allShowHs = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"allShowHs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool allShowHs
    {
      get { return _allShowHs; }
      set { _allShowHs = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_OperateNoticeMsg")]
  public partial class STC_Hongshi_OperateNoticeMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_OperateNoticeMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _typeAction = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"typeAction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int typeAction
    {
      get { return _typeAction; }
      set { _typeAction = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _beCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"beCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> beCards
    {
      get { return _beCards; }
    }
  
    private int _nextPosId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"nextPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nextPosId
    {
      get { return _nextPosId; }
      set { _nextPosId = value; }
    }
    private bool _isBeOut = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"isBeOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBeOut
    {
      get { return _isBeOut; }
      set { _isBeOut = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_SettleMsg")]
  public partial class STC_Hongshi_SettleMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_SettleMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _winPosId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"winPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winPosId
    {
      get { return _winPosId; }
      set { _winPosId = value; }
    }
    private readonly global::System.Collections.Generic.List<HongshiSettleItem> _settleLst = new global::System.Collections.Generic.List<HongshiSettleItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"settleLst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HongshiSettleItem> settleLst
    {
      get { return _settleLst; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HongshiSettleItem")]
  public partial class HongshiSettleItem : global::ProtoBuf.IExtensible
  {
    public HongshiSettleItem() {}
    
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _winIndex = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"winIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winIndex
    {
      get { return _winIndex; }
      set { _winIndex = value; }
    }
    private int _sumScore = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sumScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sumScore
    {
      get { return _sumScore; }
      set { _sumScore = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _showHs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"showHs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> showHs
    {
      get { return _showHs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_User_OnlineMsg")]
  public partial class STC_Hongshi_Table_User_OnlineMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_User_OnlineMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_ActInTable_PublishMsg")]
  public partial class STC_Hongshi_Table_ActInTable_PublishMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_ActInTable_PublishMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private SimplePlayer _player = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SimplePlayer player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SimplePlayer")]
  public partial class SimplePlayer : global::ProtoBuf.IExtensible
  {
    public SimplePlayer() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _headImg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _online = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _gameCount = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"gameCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameCount
    {
      get { return _gameCount; }
      set { _gameCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_ActInTableMsg")]
  public partial class STC_Hongshi_Table_ActInTableMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_ActInTableMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _password = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private readonly global::System.Collections.Generic.List<SimplePlayer> _playerList = new global::System.Collections.Generic.List<SimplePlayer>();
    [global::ProtoBuf.ProtoMember(6, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SimplePlayer> playerList
    {
      get { return _playerList; }
    }
  
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_Table_Quit_NotificaMsg")]
  public partial class STC_Hongshi_Table_Quit_NotificaMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_Table_Quit_NotificaMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private readonly global::System.Collections.Generic.List<SimplePlayer> _playerList = new global::System.Collections.Generic.List<SimplePlayer>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SimplePlayer> playerList
    {
      get { return _playerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_ContinueMsg")]
  public partial class STC_Hongshi_ContinueMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_ContinueMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _password = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _gameStatus = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gameStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameStatus
    {
      get { return _gameStatus; }
      set { _gameStatus = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _readyStatus = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"readyStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> readyStatus
    {
      get { return _readyStatus; }
    }
  
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _scoreList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"scoreList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> scoreList
    {
      get { return _scoreList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _cardSize = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"cardSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardSize
    {
      get { return _cardSize; }
    }
  
    private readonly global::System.Collections.Generic.List<SimplePlayer> _playerList = new global::System.Collections.Generic.List<SimplePlayer>();
    [global::ProtoBuf.ProtoMember(11, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SimplePlayer> playerList
    {
      get { return _playerList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _winIndexs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"winIndexs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> winIndexs
    {
      get { return _winIndexs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _showHsPosIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"showHsPosIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> showHsPosIds
    {
      get { return _showHsPosIds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private HongshiCardInfo _lastOutCard = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"lastOutCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public HongshiCardInfo lastOutCard
    {
      get { return _lastOutCard; }
      set { _lastOutCard = value; }
    }
    private int _nextPosId = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"nextPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nextPosId
    {
      get { return _nextPosId; }
      set { _nextPosId = value; }
    }
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private bool _isBeOut = default(bool);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"isBeOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBeOut
    {
      get { return _isBeOut; }
      set { _isBeOut = value; }
    }
    private int _multiple = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"multiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int multiple
    {
      get { return _multiple; }
      set { _multiple = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HongshiCardInfo")]
  public partial class HongshiCardInfo : global::ProtoBuf.IExtensible
  {
    public HongshiCardInfo() {}
    
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Hongshi_OfflineMsg")]
  public partial class STC_Hongshi_OfflineMsg : global::ProtoBuf.IExtensible
  {
    public STC_Hongshi_OfflineMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _password = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private int _gameStatus = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gameStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameStatus
    {
      get { return _gameStatus; }
      set { _gameStatus = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _readyStatus = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"readyStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> readyStatus
    {
      get { return _readyStatus; }
    }
  
    private int _handId = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"handId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handId
    {
      get { return _handId; }
      set { _handId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _scoreList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"scoreList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> scoreList
    {
      get { return _scoreList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _cardSize = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"cardSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardSize
    {
      get { return _cardSize; }
    }
  
    private readonly global::System.Collections.Generic.List<SimplePlayer> _playerList = new global::System.Collections.Generic.List<SimplePlayer>();
    [global::ProtoBuf.ProtoMember(11, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SimplePlayer> playerList
    {
      get { return _playerList; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _winIndexs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"winIndexs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> winIndexs
    {
      get { return _winIndexs; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _showHsPosIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"showHsPosIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> showHsPosIds
    {
      get { return _showHsPosIds; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _priCards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"priCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> priCards
    {
      get { return _priCards; }
    }
  
    private HongshiCardInfo _lastOutCard = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"lastOutCard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public HongshiCardInfo lastOutCard
    {
      get { return _lastOutCard; }
      set { _lastOutCard = value; }
    }
    private int _nextPosId = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"nextPosId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nextPosId
    {
      get { return _nextPosId; }
      set { _nextPosId = value; }
    }
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private bool _isBeOut = default(bool);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"isBeOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBeOut
    {
      get { return _isBeOut; }
      set { _isBeOut = value; }
    }
    private int _multiple = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"multiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int multiple
    {
      get { return _multiple; }
      set { _multiple = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}