//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProjectA_SubA_ProtoDefine.proto
namespace ProjectA_SubA_ProtoDefine
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LHandshakeMQData")]
  public partial class LHandshakeMQData : global::ProtoBuf.IExtensible
  {
    public LHandshakeMQData() {}
    
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EconomyInfo")]
  public partial class EconomyInfo : global::ProtoBuf.IExtensible
  {
    public EconomyInfo() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _gold = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private int _payCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"payCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int payCount
    {
      get { return _payCount; }
      set { _payCount = value; }
    }
    private int _payTotal = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"payTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int payTotal
    {
      get { return _payTotal; }
      set { _payTotal = value; }
    }
    private long _lastPayTime = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lastPayTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastPayTime
    {
      get { return _lastPayTime; }
      set { _lastPayTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SocialInfo")]
  public partial class SocialInfo : global::ProtoBuf.IExtensible
  {
    public SocialInfo() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _headImg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private string _introduce = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"introduce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string introduce
    {
      get { return _introduce; }
      set { _introduce = value; }
    }
    private string _mobile = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mobile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mobile
    {
      get { return _mobile; }
      set { _mobile = value; }
    }
    private string _idcard = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"idcard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string idcard
    {
      get { return _idcard; }
      set { _idcard = value; }
    }
    private string _country = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"country", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string country
    {
      get { return _country; }
      set { _country = value; }
    }
    private string _province = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"province", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string province
    {
      get { return _province; }
      set { _province = value; }
    }
    private int _city = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"city", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int city
    {
      get { return _city; }
      set { _city = value; }
    }
    private string _address = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string address
    {
      get { return _address; }
      set { _address = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserStatus")]
  public partial class UserStatus : global::ProtoBuf.IExtensible
  {
    public UserStatus() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _isOnline = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isOnline", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isOnline
    {
      get { return _isOnline; }
      set { _isOnline = value; }
    }
    private string _createRoomIds = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"createRoomIds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string createRoomIds
    {
      get { return _createRoomIds; }
      set { _createRoomIds = value; }
    }
    private string _lastRoomId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lastRoomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string lastRoomId
    {
      get { return _lastRoomId; }
      set { _lastRoomId = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_GetUserInfoMsg")]
  public partial class CTS_GetUserInfoMsg : global::ProtoBuf.IExtensible
  {
    public CTS_GetUserInfoMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Lobby_HeartbeatMsg")]
  public partial class CTS_Lobby_HeartbeatMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Lobby_HeartbeatMsg() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_LoginMsg")]
  public partial class CTS_LoginMsg : global::ProtoBuf.IExtensible
  {
    public CTS_LoginMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _machineCode = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"machineCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string machineCode
    {
      get { return _machineCode; }
      set { _machineCode = value; }
    }
    private string _account = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _comeFrom = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"comeFrom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string comeFrom
    {
      get { return _comeFrom; }
      set { _comeFrom = value; }
    }
    private string _sessionid = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sessionid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sessionid
    {
      get { return _sessionid; }
      set { _sessionid = value; }
    }
    private int _regChannel = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"regChannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int regChannel
    {
      get { return _regChannel; }
      set { _regChannel = value; }
    }
    private string _os = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"os", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string os
    {
      get { return _os; }
      set { _os = value; }
    }
    private string _IMEI = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"IMEI", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IMEI
    {
      get { return _IMEI; }
      set { _IMEI = value; }
    }
    private string _loginIp = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"loginIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loginIp
    {
      get { return _loginIp; }
      set { _loginIp = value; }
    }
    private SocialInfo _socialInfo = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"socialInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SocialInfo socialInfo
    {
      get { return _socialInfo; }
      set { _socialInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_PlatformLoginMsg")]
  public partial class CTS_PlatformLoginMsg : global::ProtoBuf.IExtensible
  {
    public CTS_PlatformLoginMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _comeFrom = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"comeFrom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string comeFrom
    {
      get { return _comeFrom; }
      set { _comeFrom = value; }
    }
    private string _sessionid = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sessionid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sessionid
    {
      get { return _sessionid; }
      set { _sessionid = value; }
    }
    private string _refreshToken = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"refreshToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string refreshToken
    {
      get { return _refreshToken; }
      set { _refreshToken = value; }
    }
    private int _regChannel = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"regChannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int regChannel
    {
      get { return _regChannel; }
      set { _regChannel = value; }
    }
    private string _os = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"os", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string os
    {
      get { return _os; }
      set { _os = value; }
    }
    private string _IMEI = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"IMEI", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IMEI
    {
      get { return _IMEI; }
      set { _IMEI = value; }
    }
    private string _loginIp = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"loginIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loginIp
    {
      get { return _loginIp; }
      set { _loginIp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Lobby_HeartbeatMsg")]
  public partial class STC_Lobby_HeartbeatMsg : global::ProtoBuf.IExtensible
  {
    public STC_Lobby_HeartbeatMsg() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_LoginMsg")]
  public partial class STC_LoginMsg : global::ProtoBuf.IExtensible
  {
    public STC_LoginMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _session = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string session
    {
      get { return _session; }
      set { _session = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private string _loginIp = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"loginIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loginIp
    {
      get { return _loginIp; }
      set { _loginIp = value; }
    }
    private SocialInfo _socialInfo = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"socialInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SocialInfo socialInfo
    {
      get { return _socialInfo; }
      set { _socialInfo = value; }
    }
    private EconomyInfo _economyInfo = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"economyInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public EconomyInfo economyInfo
    {
      get { return _economyInfo; }
      set { _economyInfo = value; }
    }
    private UserStatus _userStatus = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"userStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UserStatus userStatus
    {
      get { return _userStatus; }
      set { _userStatus = value; }
    }
    private string _account = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _gameServerIp = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"gameServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameServerIp
    {
      get { return _gameServerIp; }
      set { _gameServerIp = value; }
    }
    private string _gameServerPort = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"gameServerPort", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameServerPort
    {
      get { return _gameServerPort; }
      set { _gameServerPort = value; }
    }
    private string _chatPort = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"chatPort", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chatPort
    {
      get { return _chatPort; }
      set { _chatPort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_PlatformLoginMsg")]
  public partial class STC_PlatformLoginMsg : global::ProtoBuf.IExtensible
  {
    public STC_PlatformLoginMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _refreshToken = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"refreshToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string refreshToken
    {
      get { return _refreshToken; }
      set { _refreshToken = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private string _loginIp = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"loginIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loginIp
    {
      get { return _loginIp; }
      set { _loginIp = value; }
    }
    private SocialInfo _socialInfo = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"socialInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SocialInfo socialInfo
    {
      get { return _socialInfo; }
      set { _socialInfo = value; }
    }
    private EconomyInfo _economyInfo = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"economyInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public EconomyInfo economyInfo
    {
      get { return _economyInfo; }
      set { _economyInfo = value; }
    }
    private UserStatus _userStatus = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"userStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UserStatus userStatus
    {
      get { return _userStatus; }
      set { _userStatus = value; }
    }
    private string _account = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _session = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string session
    {
      get { return _session; }
      set { _session = value; }
    }
    private string _platformStr = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"platformStr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string platformStr
    {
      get { return _platformStr; }
      set { _platformStr = value; }
    }
    private string _gameServerIp = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"gameServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameServerIp
    {
      get { return _gameServerIp; }
      set { _gameServerIp = value; }
    }
    private string _gameServerPort = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"gameServerPort", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameServerPort
    {
      get { return _gameServerPort; }
      set { _gameServerPort = value; }
    }
    private string _chatPort = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"chatPort", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chatPort
    {
      get { return _chatPort; }
      set { _chatPort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_UserInfoMsg")]
  public partial class STC_UserInfoMsg : global::ProtoBuf.IExtensible
  {
    public STC_UserInfoMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _account = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private int _regChannel = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"regChannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int regChannel
    {
      get { return _regChannel; }
      set { _regChannel = value; }
    }
    private string _os = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"os", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string os
    {
      get { return _os; }
      set { _os = value; }
    }
    private string _loginIp = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"loginIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string loginIp
    {
      get { return _loginIp; }
      set { _loginIp = value; }
    }
    private SocialInfo _socialInfo = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"socialInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SocialInfo socialInfo
    {
      get { return _socialInfo; }
      set { _socialInfo = value; }
    }
    private EconomyInfo _economyInfo = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"economyInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public EconomyInfo economyInfo
    {
      get { return _economyInfo; }
      set { _economyInfo = value; }
    }
    private UserStatus _userStatus = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"userStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UserStatus userStatus
    {
      get { return _userStatus; }
      set { _userStatus = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_UserTableInfoMsg")]
  public partial class STC_UserTableInfoMsg : global::ProtoBuf.IExtensible
  {
    public STC_UserTableInfoMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private readonly global::System.Collections.Generic.List<UserTableItem> _tableList = new global::System.Collections.Generic.List<UserTableItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tableList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UserTableItem> tableList
    {
      get { return _tableList; }
    }
  
    private string _sessionId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sessionId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sessionId
    {
      get { return _sessionId; }
      set { _sessionId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserTableItem")]
  public partial class UserTableItem : global::ProtoBuf.IExtensible
  {
    public UserTableItem() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private bool _isLastTable = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isLastTable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isLastTable
    {
      get { return _isLastTable; }
      set { _isLastTable = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Chat_SendMsg")]
  public partial class CTS_Chat_SendMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Chat_SendMsg() {}
    
    private byte[] _msg = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _consumeIds = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"consumeIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> consumeIds
    {
      get { return _consumeIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Chat_ContentMsg")]
  public partial class STC_Chat_ContentMsg : global::ProtoBuf.IExtensible
  {
    public STC_Chat_ContentMsg() {}
    
    private byte[] _msg = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private long _sendId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sendId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sendId
    {
      get { return _sendId; }
      set { _sendId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Pay_SucceedMsg")]
  public partial class STC_Pay_SucceedMsg : global::ProtoBuf.IExtensible
  {
    public STC_Pay_SucceedMsg() {}
    
    private string _orderId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"orderId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string orderId
    {
      get { return _orderId; }
      set { _orderId = value; }
    }
    private int _diamond = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamond
    {
      get { return _diamond; }
      set { _diamond = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_ErrorMsgMsg")]
  public partial class STC_ErrorMsgMsg : global::ProtoBuf.IExtensible
  {
    public STC_ErrorMsgMsg() {}
    
    private int _errId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errId
    {
      get { return _errId; }
      set { _errId = value; }
    }
    private string _errMsg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errMsg
    {
      get { return _errMsg; }
      set { _errMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_TableSettleMsg")]
  public partial class CTS_TableSettleMsg : global::ProtoBuf.IExtensible
  {
    public CTS_TableSettleMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_ActExitTableMsg")]
  public partial class CTS_Table_ActExitTableMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_ActExitTableMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_ActInTableMsg")]
  public partial class CTS_Table_ActInTableMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_ActInTableMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_CreateMsg")]
  public partial class CTS_Table_CreateMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_CreateMsg() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_DissolveRequestMsg")]
  public partial class CTS_Table_DissolveRequestMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_DissolveRequestMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_DissolveVoteMsg")]
  public partial class CTS_Table_DissolveVoteMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_DissolveVoteMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _vote = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"vote", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vote
    {
      get { return _vote; }
      set { _vote = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CTS_Table_HeartbeatMsg")]
  public partial class CTS_Table_HeartbeatMsg : global::ProtoBuf.IExtensible
  {
    public CTS_Table_HeartbeatMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_TableSettleMsg")]
  public partial class STC_TableSettleMsg : global::ProtoBuf.IExtensible
  {
    public STC_TableSettleMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handTotal = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"handTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handTotal
    {
      get { return _handTotal; }
      set { _handTotal = value; }
    }
    private long _createTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private long _finishTime = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"finishTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long finishTime
    {
      get { return _finishTime; }
      set { _finishTime = value; }
    }
    private string _masterUserHeadImg = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"masterUserHeadImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string masterUserHeadImg
    {
      get { return _masterUserHeadImg; }
      set { _masterUserHeadImg = value; }
    }
    private int _seatNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"seatNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seatNum
    {
      get { return _seatNum; }
      set { _seatNum = value; }
    }
    private readonly global::System.Collections.Generic.List<PlayerGrade> _gradeList = new global::System.Collections.Generic.List<PlayerGrade>();
    [global::ProtoBuf.ProtoMember(8, Name=@"gradeList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerGrade> gradeList
    {
      get { return _gradeList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerGrade")]
  public partial class PlayerGrade : global::ProtoBuf.IExtensible
  {
    public PlayerGrade() {}
    
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _winCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"winCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winCount
    {
      get { return _winCount; }
      set { _winCount = value; }
    }
    private int _zhadanCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"zhadanCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zhadanCount
    {
      get { return _zhadanCount; }
      set { _zhadanCount = value; }
    }
    private int _handMaxGrade = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handMaxGrade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handMaxGrade
    {
      get { return _handMaxGrade; }
      set { _handMaxGrade = value; }
    }
    private int _gradeCount = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gradeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gradeCount
    {
      get { return _gradeCount; }
      set { _gradeCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_ActExitTableMsg")]
  public partial class STC_Table_ActExitTableMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_ActExitTableMsg() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_ActInTableMsg")]
  public partial class STC_Table_ActInTableMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_ActInTableMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _password = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private readonly global::System.Collections.Generic.List<SimplePlayer> _playerList = new global::System.Collections.Generic.List<SimplePlayer>();
    [global::ProtoBuf.ProtoMember(6, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SimplePlayer> playerList
    {
      get { return _playerList; }
    }
  
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SimplePlayer")]
  public partial class SimplePlayer : global::ProtoBuf.IExtensible
  {
    public SimplePlayer() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private int _gender = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _headImg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _online = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeoError")]
  public partial class TeoError : global::ProtoBuf.IExtensible
  {
    public TeoError() {}
    
    private int _errId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errId
    {
      get { return _errId; }
      set { _errId = value; }
    }
    private string _errMsg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errMsg
    {
      get { return _errMsg; }
      set { _errMsg = value; }
    }
    private bool _isShow = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isShow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isShow
    {
      get { return _isShow; }
      set { _isShow = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_ActInTable_PublishMsg")]
  public partial class STC_Table_ActInTable_PublishMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_ActInTable_PublishMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private SimplePlayer _player = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public SimplePlayer player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_CreateMsg")]
  public partial class STC_Table_CreateMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_CreateMsg() {}
    
    private int _gameId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private string _tableName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tableName
    {
      get { return _tableName; }
      set { _tableName = value; }
    }
    private int _handNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"handNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int handNum
    {
      get { return _handNum; }
      set { _handNum = value; }
    }
    private int _postionNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"postionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int postionNum
    {
      get { return _postionNum; }
      set { _postionNum = value; }
    }
    private CreateResult _createResult = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"createResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CreateResult createResult
    {
      get { return _createResult; }
      set { _createResult = value; }
    }
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateResult")]
  public partial class CreateResult : global::ProtoBuf.IExtensible
  {
    public CreateResult() {}
    
    private long _masterId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"masterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long masterId
    {
      get { return _masterId; }
      set { _masterId = value; }
    }
    private int _password = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int password
    {
      get { return _password; }
      set { _password = value; }
    }
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _createTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long createTime
    {
      get { return _createTime; }
      set { _createTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_DissolveRequestMsg")]
  public partial class STC_Table_DissolveRequestMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_DissolveRequestMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private TeoError _error = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TeoError error
    {
      get { return _error; }
      set { _error = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_DissolveResultMsg")]
  public partial class STC_Table_DissolveResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_DissolveResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_DissolveVoteMsg")]
  public partial class STC_Table_DissolveVoteMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_DissolveVoteMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private long _reqUserId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reqUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long reqUserId
    {
      get { return _reqUserId; }
      set { _reqUserId = value; }
    }
    private string _reqNickName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reqNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reqNickName
    {
      get { return _reqNickName; }
      set { _reqNickName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_DissolveVoteResultMsg")]
  public partial class STC_Table_DissolveVoteResultMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_DissolveVoteResultMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"STC_Table_HeartbeatMsg")]
  public partial class STC_Table_HeartbeatMsg : global::ProtoBuf.IExtensible
  {
    public STC_Table_HeartbeatMsg() {}
    
    private long _tableId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tableId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tableId
    {
      get { return _tableId; }
      set { _tableId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}